apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ $.Values.Image }}
          ports:
            - containerPort: {{ .Values.probesPort }}
          env:
            - name: PROBES_PORT
              value: "{{ .Values.probesPort }}"
            {{- range .Values.secretVars }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: {{ . }}
            {{- end }}
          imagePullPolicy: Always
          livenessProbe:
            timeoutSeconds: 3
            httpGet:
              path: /healthz
              port: {{ .Values.probesPort }}
          readinessProbe:
            timeoutSeconds: 3
            httpGet:
              path: /readyz
              port: {{ .Values.probesPort }}
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
      terminationGracePeriodSeconds: 5